datapath <- "D:/Documentos/Training/Coursera/ExploratoryDataAnalysis/CourseProject1/household_power_consumption.txt"
data <- read.table(datapath, sep = ";", header = TRUE, colClasses = "character")
data$Date <- as.Date(data$Date, "%d/%m/%Y")

library(dplyr)
cran <- tbl_df(data)
rm("data")
powerdata <- filter(cran, Date == "2007-02-01" | Date == "2007-02-02")
powerdata$Global_active_power <- as.numeric(powerdata$Global_active_power)
powerdata$Sub_metering_1 <- as.numeric(powerdata$Sub_metering_1)
powerdata$Sub_metering_2 <- as.numeric(powerdata$Sub_metering_2)
powerdata$Sub_metering_3 <- as.numeric(powerdata$Sub_metering_3)
powerdata$Voltage <- as.numeric(powerdata$Voltage)
powerdata$Global_reactive_power <- as.numeric(powerdata$Global_reactive_power)
powerdata2 <- mutate(powerdata, datetime = paste(Date, Time))
powerdata2$datetime <- strptime(powerdata2$datetime, format = "%Y-%m-%d %H:%M:%S")
png(file = "plot4.png", width = 480, height = 480, units = "px")
par(mfcol = c(2, 2), mar = c(5, 4, 4, 2))
with(powerdata2, plot(datetime, Global_active_power, type = "l", xlab = " ", ylab = "Global Active Power"))
with(powerdata2, plot(datetime, Sub_metering_1, type = "l", xlab = " ", ylab = "Energy sub metering"))
with(powerdata2, lines(datetime, Sub_metering_2, col = "red"))
with(powerdata2, lines(datetime, Sub_metering_3, col = "blue"))
legend("topright", lwd = c(1, 1, 1), col = c("black", "red", "blue"),
       legend = c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), bty = "n")
with(powerdata2, plot(datetime, Voltage, type = "l"))
with(powerdata2, plot(datetime, Global_reactive_power, type = "l"))
dev.off()
